[package]
name = "auto_test"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
walkdir = "2"
syn = { version = "2", features = ["full"] }
quote = "1.0.42"
